### PR TITLE
Add needed alarm permission for A12

### PR DESCRIPTION
**Pull request by machiav3lli**
The PR also includes updates to dependencies, AGP and app config

### CODE REVIEW

**Comment by qw123wh** [comment]
i can't compile the app with android studio, problem with build.gradle 'com.android.tools.build:gradle:7.0.3'. 
Anyway thanks for your help. On one thing, however, I disagree. In my opinion, the permission of the telephone is not necessary. In fact, the app performs well on the various devices that I have even without that permission.

**Comment by qw123wh** [comment]
can you help me with the theme to solve issue #2 ? There is already a pull request for the theme but it is very buggy

**Comment by machiav3lli** [comment]
@qw123wh you gotta update AS to the latest stable.

**Comment by machiav3lli** [comment]
@qw123wh the telephone permission is needed to check if there's a call running to not interrupt it. This is one of the SDK changes

**Comment by machiav3lli** [comment]
@qw123wh and yeah, I can gladly help with #2, but it'll have to wait some time, as am busy with my other projects :)

**Comment by qw123wh** [comment]
@machiav3lli thanks again, as soon as you have time let me know, i would like to make other changes with your help

**Pull request merged**
